config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :countries, param: :name, :only => [:show]
  resources :guides
  get 'trouver-un-guide', to: 'countries#index', as: :countries
  get 'pages/a_savoir'
  get 'admin/upload-guides', to: 'guides#upload_guides', as: :upload_guides
  post 'admin/upload-guides', to: 'guides#post_upload_guides', as: :post_upload_guides
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :traveler
  belongs_to :guide
end

app/models/country.rb
class Country < ApplicationRecord
  has_one :country_photo, dependent: :destroy
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/country_offering.rb
class CountryOffering < ApplicationRecord
  belongs_to :guide
  belongs_to :country
end

app/models/country_photo.rb
class CountryPhoto < ApplicationRecord
  belongs_to :country
end

app/models/guide.rb
class Guide < ApplicationRecord
  belongs_to :guide_organization, optional: true
  belongs_to :guide_contact_info, optional: true
  belongs_to :user
  has_many  :country_offerings, dependent: :destroy
  has_many  :guide_specialities, dependent: :destroy
  has_many  :guide_reviews, dependent: :destroy
  has_many  :spoken_languages, dependent: :destroy
  extend FriendlyId
  friendly_id :full_name, use: :slugged


  def full_name
    unless self.user.nil?
    self.user.first_name + ' ' + self.user.last_name
    end
  end

end

app/models/guide_contact_info.rb
class GuideContactInfo < ApplicationRecord
end

app/models/guide_organization.rb
class GuideOrganization < ApplicationRecord
end

app/models/guide_review.rb
class GuideReview < ApplicationRecord
  belongs_to :guide
  belongs_to :review
  belongs_to :traveler
end

app/models/guide_speciality.rb
class GuideSpeciality < ApplicationRecord
  belongs_to :speciality
  belongs_to :guide
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/speciality.rb
class Speciality < ApplicationRecord
end

app/models/spoken_language.rb
class SpokenLanguage < ApplicationRecord
  belongs_to :language
  belongs_to :guide
end

app/models/traveler.rb
class Traveler < ApplicationRecord
  belongs_to :user
  has_many :guide_reviews
  extend FriendlyId
  friendly_id :full_name, use: :slugged


  def full_name
    self.user.first_name + ' ' + self.user.last_name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]
  has_one :guide
  has_one :traveler

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/models/visiting_interest.rb
class VisitingInterest < ApplicationRecord
  belongs_to :country
  belongs_to :traveler
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SoGuide</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/_banner.html.erb
<div class="banner" style="background-image:url('<%= asset_path("banner.jpg") %>')">
  <div class="banner-content">
    <h1>Une selection des guides locaux recommandés par tous leurs clients</h1>
    <p>Pour tous vos treks et voyages hors des sentiers battus</p>
  </div>
</div>

app/views/pages/a_savoir.html.erb
<div class="banner" style="background-image:linear-gradient(-225deg, rgba(0, 78, 20, 0.6) 0%, rgba(0, 77, 20, 0.34) 50%), url('<%= asset_path("banner-a-savoir.jpg") %>')">
  <div class="banner-content">


  </div>
</div>
<div class="padded"></div>

<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <h2>Préparer son voyage avec un guide</h2>
      <p>7 questions à se poser</p>
      <p>Pour vous simplifier la vie, l’équipe SoGuide a répertorié ci-dessous les 7 grandes questions à poser et à se poser avant de confirmer son voyage avec un guide indépendant. Chacun de ces points peut avoir un impact important sur le prix et sur la qualité de votre voyage donc pensez à vérifier que vous avez toutes les clés en main pour bien choisir ! Dans tous les cas, n’hésitez pas à imprimer vos e-mails avant de partir car on n’est jamais trop prudent !</p>
    </div>
    </div>
    <div class="row">
<div class="padded-little"></div>
    <div class="col-md-6 card-img-pratique"  style="    border-top-left-radius: 30%;background-image:url('<%= asset_path("Pratique-1.jpg") %>')">
    </div>

    <div class="col-md-6 card-img-pratique"  style="    border-top-right-radius: 30%;background-image:url('<%= asset_path("Pratique-2.jpg") %>')">
    </div>
  </div>
</div>



<div class="padded"></div>


<div class="container">
  <div class="row">
    <div class="col-md-6">
      <p class="text-center">
        <button class="btn-default" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          La taille de votre groupe
        </button>
      </p>
      <div class="collapse" id="collapseExample">
        <div class="card card-block">
          <span  class="collapse-span">Abordez la question de la taille du groupe avec le guide !</span>
          <p  class="collapse-span">Un des principaux intérêts de partir avec un guide indépendant est de bénéficier d’un service particulier et d’éviter les « Tours » où se mêlent familles, personnes âgées et jeunes adolescents. Au sein de larges structures, les départs ne sont garantis qu’à partir d’un certain nombre de participants : les groupes sont donc souvent composés de 10 à 15 personnes. On comprend facilement les problèmes que cela peut poser pour des voyages culturels et encore plus pour des treks – pour lesquels les rythmes de marche peuvent fortement varier entre les participants.</p>

          <p class="collapse-span">Que vous soyez seul, en couple entre amis ou en famille, le guide indépendant s’adaptera toujours à votre situation et les variations de prix resteront relativement faibles au regard de ce qui se pratique généralement dans ce secteur. N’hésitez donc jamais à demander confirmation que vous ne serez pas rattachés à un groupe plus large – sauf bien entendu si vous le désirez.</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <p class="text-center">
        <button class="btn-default" type="button" data-toggle="collapse" data-target="#collapseExample2" aria-expanded="false" aria-controls="collapseExample">
          Le transfert de guide
        </button>
      </p>
      <div class="collapse" id="collapseExample2">
        <div class="card card-block">
          <span  class="collapse-span">Assurez-vous que votre interlocuteur sera bien votre guide !</span>
          <p  class="collapse-span">C’est sans doute une des pratiques les plus répandues et les plus problématiques pour la profession. En effet, si un guide commence à bénéficier d’une bonne réputation, le nombre de clients va rapidement augmenter. Ne pouvant répondre à la demande croissante, le guide va devoir faire appel à des amis ou de la famille pour l’aider. Cependant la réussite d’un voyage dépend souvent plus de la personnalité du guide que de la réputation de l’agence: un guide très compétent peut redistribuer ses clients – moyennant commission – à d’autres guides moins compétents.</p>
          <p class="collapse-span">Pour éviter de rencontrer ce problème deux solutions s’offrent à vous : (1) assurez vous que le guide en question sera bien votre accompagnateur lors de votre voyage – si besoin, imprimez vos échanges mails, (2) si l’on vous explique qu’un autre guide s’occupera de vous, recherchez des avis sur ce guide que ce soit dans les commentaires répertoriés sur SoGuide ou sur internet en général. Dans tous les cas, sachez que les bons guides auront tendance à s’associer à des guides compétents : pour vous aider dans votre choix, nous avons répertorié les principaux guides associés sur chacune des pages de nos guides référencés. Si vous rencontrez un problème de ce type, n’hésitez pas à nous contacter pour que nous puissions mettre en garde les futurs utilisateurs.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="padded"></div>
  <div class="row">
    <div class="col-md-6 card-img-pratique"  style="background-image:url('<%= asset_path("Pratique-3.jpg") %>')">
    </div>
    <div class="col-md-6 card-img-pratique"  style="background-image:url('<%= asset_path("Pratique-4.jpg") %>')">
    </div>
    </div>
</div>
</div>
<div class="padded"></div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <p class="text-center">
        <button class="btn-default" type="button" data-toggle="collapse" data-target="#collapseExample3" aria-expanded="false" aria-controls="collapseExample">
          Les compétences de l'équipe
        </button>
      </p>
      <div class="collapse" id="collapseExample3">
        <div class="card card-block">
          <span  class="collapse-span">Assurez-vous des compétences de votre guide !</span>
          <p  class="collapse-span">Un guide culturel n’est pas nécessairement chauffeur et inversement. Une des questions les plus importantes que vous aurez à poser avant de confirmer votre voyage porte sur la composition précise de l’équipe et le rôle de chacun.</p>

          <p class="collapse-span">Si vous partez en voyage culturel, votre chauffeur est-il capable de vous expliquer l’histoire de certains monuments, a-t-il l’autorisation de rentrer dans les sites touristiques, votre guide est-il aussi le chauffeur ou y-a-t-il une autre personne ? Avez-vous un cuisinier, un porteur durant votre trek ? Toutes ces questions sont primordiales pour bien comprendre dans quoi vous vous engagez et les informations répertoriées dans la fiche de guide ne suffisent pas toujours à faire les bons choix.</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <p class="text-center">
        <button class="btn-default" type="button" data-toggle="collapse" data-target="#collapseExample4" aria-expanded="false" aria-controls="collapseExample">
          Les transports
        </button>
      </p>
      <div class="collapse" id="collapseExample4">
        <div class="card card-block">
          <span  class="collapse-span">Etudiez la question des transports avec votre guide !</span>
          <p  class="collapse-span">Dans la plupart des pays en développement, les transports sont un point crucial dans la réussite d’un séjour. Si vous réservez un trek, il est important de demander à quel moment commence la prise en charge, les zones de randonnée étant parfois situées à plusieurs heures de voiture.</p>
          <p class="collapse-span">Dans certains cas, les guides préféreront opter pour des transports publics sans que vous ne soyez vraiment au courant. Le mieux est donc d’être bien clair dès le départ. Si vous réservez un chauffeur ou un guide culturel, il peut être utile de vérifier l’état, l’âge et la taille de la voiture. Certains détails, comme la présence de climatisation, peuvent vite s’avérer d’une importance capitale pour de nombreuses destinations</p>
        </div>
      </div>
    </div>
  </div>
  <div class="padded"></div>
  <div class="row">
    <div class="col-md-6 card-img-pratique"  style="border-bottom-left-radius: 10%;background-image:url('<%= asset_path("Pratique-5.jpg") %>')">
    </div>
    <div class="col-md-6 card-img-pratique"  style="border-bottom-right-radius: 10%;background-image:url('<%= asset_path("Pratique-6.jpg") %>')">
    </div>
    </div>
</div>
</div>

<div class="padded"></div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <p class="text-center">
        <button class="btn-default" type="button" data-toggle="collapse" data-target="#collapseExample5" aria-expanded="false" aria-controls="collapseExample">
          Les logements
        </button>
      </p>
      <div class="collapse" id="collapseExample5">
        <div class="card card-block">
          <span  class="collapse-span">Faites savoir à votre guide le type de logement qui vous correspond !</span>
          <p  class="collapse-span">Lorsque vous organisez un trek ou un séjour touristique, un des principaux coûts de votre guide sera le logement. Ainsi la différence de prix entre deux propositions de séjour peut parfois s’expliquer par la différence de logement. Pour un guide, le coût n’est pas le même s’il vous loge sous tente, chez l’habitant, en gîte ou en hôtel. C’est donc une question importante à  poser pour pouvoir bien comparer les propositions qui vous sont faites!</p>

          <p class="collapse-span">Si vous partez en randonnée il vous faudra souvent réserver des hôtels en ville avant et après le trek. Les guides et les chauffeurs ont tout intérêt à vous réserver des hébergements en ville à prix avantageux: d’une part ils disposent d’un réseau de contacts locaux, d’autre part il bénéficient de « prix d’agence » bien inférieurs à ceux du grand public. C’est d’ailleurs sur ces réservations que beaucoup de guides indépendants font leurs marges. Quelques rares cas mis à part, la différence entre les prix grand public et les prix d’agences permettent à la fois aux guides de faire des bénéfices et aux clients de faire de bonnes affaires! Si vous ne souhaitez pas passer des heures sur booking.com à dénicher la perle rare, nous vous recommandons donc de passer par vos guides pour réserver vos logements en ville.</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <p class="text-center">
        <button class="btn-default" type="button" data-toggle="collapse" data-target="#collapseExample6" aria-expanded="false" aria-controls="collapseExample">
          Les extras
        </button>
      </p>
      <div class="collapse" id="collapseExample6">
        <div class="card card-block">
          <span  class="collapse-span">Estimez vos dépenses « extras » avec votre guide !</span>
          <p  class="collapse-span">Pour augmenter leurs revenus, certains guides peuvent omettre certaines dépenses que vous pourriez avoir sur place. Pensez donc à demander ce qu’inclut et ce que n’inclut pas la prestation. Si vous prévoyez des visites avec un chauffeur, demandez-lui si les entrées dans les monuments sont à votre charge ou encore si des guides spécifiques sont nécessaires sur certains sites.</p>
          <p class="collapse-span">Si vous partez en trek, il vous faut tout d’abord savoir si les permis de treks sont compris dans le prix de votre séjour. Ensuite, n’hésitez pas à vous renseigner sur les équipements nécessaires : bâtons de marches, sacs de couchage, crampons, etc. Si vous ne pouvez vous procurer certains équipements, assurez-vous de connaître le prix de la location sur place et avisez en fonction. Enfin, n’hésitez pas à bien relire les mails qui vous ont été envoyés par vos guides : les boissons sont-elles comprises, des suppléments sont-ils nécessaires pour des logements de qualité supérieure ?</p>
        </div>
      </div>
    </div>
  </div>
  <div class="padded"></div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3 card-img-pratique"  style="background-image:url('<%= asset_path("Pratique-7.jpg") %>')">
    </div>
    <div class="padded-little"></div>
        <div class="col-md-6 col-md-offset-3">
      <p class="text-center">
        <button class="btn-default" type="button" data-toggle="collapse" data-target="#collapseExample7" aria-expanded="false" aria-controls="collapseExample">
          Le mode de paiement
        </button>
      </p>
      <div class="collapse" id="collapseExample7">
        <div class="card card-block">
          <span  class="collapse-span">Abordez la question du paiement dès que possible !</span>
          <p  class="collapse-span">Plus la structure est importante, plus le règlement à payer en amont sera élevé. Les tours opérateurs vous demanderont de tout payer en avance, les agences locales vous demanderont un acompte, tandis que la plupart des guides indépendants demanderont à être payés en fin de séjour.</p>
          <p class="collapse-span">Nous vous conseillons de privilégier cette dernière option (exclusion faite des cas spécifiques comme les safaris ou autres voyages plus onéreux), non pas seulement pour vous épargner les frais de virements internationaux, mais aussi pour vous garantir le meilleur séjour possible – le guide ne pouvant se permettre de modifier sa prestation s’il n’a pas encore été payé. Dans tous les cas, rappelez-vous qu’un guide ou une agence tient plus à sa réputation qu’au prix de votre séjour !</p>
        </div>
      </div>
    </div>
    </div>
</div>
</div>
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
$(document).ready(function() {

});
  <% end %>
<% end %>

app/views/pages/add_country.html.erb
<div class="padded-little"></div>

<%= simple_form_for(@country) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :full_description %>
  <%= f.input :address %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/pages/home.html.erb
<%= render "banner" %>
<div class="container">
  <div class="row text-center">
    <div class="col-md-12 partenaires-wrapper second-part">
    <%= link_to "http://www.capcampus.com/campus-live-474/en-voyage-suivez-le-guide-oui-mais-lequel-a37740.html", target: :_blank  do %>
    <%= image_tag "Logo-Cap-Campus.jpg", class: "logo-partenaire" %>
    <% end %>
    <%= link_to "http://earlyadoptersparis.com/soguide-une-plateforme-de-voyage-pour-contacter-des-guides-locaux-a-letranger-284", target: :_blank  do %>
    <%= image_tag "Logo-Early-Adopters.jpg", class: "logo-partenaire" %>
    <% end %>
    <%= link_to "http://www.tourmag.com/SoGuide-veut-aider-les-guides-touristiques-dans-les-pays-en-developpement_a79034.html", target: :_blank  do %>
    <%= image_tag "Logo-I-tourisme.jpg", class: "logo-partenaire" %>
    <% end %>
    <%= link_to "http://www.quotidiendutourisme.com/site/blog-a-part-destination-production-profession-site/production-collaboratif-soguide-com-pour-trouver-un-guide-touristique-a-son-pied-97325.html", target: :_blank  do %>
    <%= image_tag "Logo-Le-Quotidien.jpg", class: "logo-partenaire" %>
    <% end %>
    <%= link_to "http://www.levoyageur.net/article-soguide-une-communaute-de-partage-349.html#.Wa7vBkpJa2x", target: :_blank  do %>
    <%= image_tag "Logo-Le-Voyageur.jpg", class: "logo-partenaire" %>
    <% end %>
    <%= link_to "http://www.levoyageur.net/article-soguide-une-communaute-de-partage-349.html#.Wa7vBkpJa2x", target: :_blank  do %>
    <%= image_tag "Logo-voyager-mag.jpg", class: "logo-partenaire" %>
    <% end %>
    </div>
  </div>
</div>

<%= render "mid-banner" %>


<div class="container">
  <div class="row text-center">
      <h3>Astuces & Conseils</h3>

    <div class="col-md-4 card-menu">
    <div class="card-menu-body">
    <%= link_to pages_a_savoir_path do %>
      <%= image_tag asset_path("rome-image-gallery-7-300x200.jpg"), class: "img-card-menu"%>

      <h3 class="title-link">Préparer son voyage</h3>
      <p>L’équipe SoGuide a répertorié pour vous 7 questions à se poser pour préparer au mieux son voyage avec un guide.</p>
    <% end %>
    </div>
    </div>

    <div class="col-md-4 card-menu">
    <div class="card-menu-body">
    <%= link_to pages_a_savoir_path do %>
      <%= image_tag asset_path("machu-picchu-image-gallery-4-300x200.jpg"), class: "img-card-menu"%>

      <h3 class="title-link">Le Concept</h3>
      <p>Découvrez comment d’un besoin puis d’un constat nous sommes arrivés à l’idée de So Guide.</p>
    <% end %>
    </div>
    </div>

    <div class="col-md-4 card-menu">
    <div class="card-menu-body">
    <%= link_to pages_a_savoir_path do %>
      <%= image_tag asset_path("http://www.so-guide.com/dev/wp-content/uploads/2016/04/spain-image-gallery-11-300x200.jpg"), class: "img-card-menu"%>

      <h3 class="title-link">La Communauté</h3>
      <p>Faites vivre la communauté SoGuide en partageant votre expérience sur les réseaux sociaux</p>
    <% end %>
    </div>
    </div>
  </div>

<div class="padded-little"></div>
</div>

<div class="padded-little"></div>
</div>
<div class="padded-little"></div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_log_in_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="border-radius: 20px;">
      <div class="modal-header text-center">
        <h5 class="modal-title" id="exampleModalLabel" style="margin-bottom: -2rem;"><%= image_tag('logo.png', class:"logo-nav") %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
          <div class="container-fluid text-center">
            <div class="row">
              <div class="col-md-12 modal-title greened">Connectez vous sur votre espace Soguide !</div>
              <div class="col-md-12">

                <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                  <div class="form-inputs" style="padding:2rem">
                    <%= f.label :email, "Mail d'identifiant", class:"modal-title" %>
                    <%= f.input :email, required: false, autofocus: true, label: false %>
                    <%= f.label :password, "Mot de passe", class:"modal-title" %>
                    <%= f.input :password, required: false, label: false %>
                    <div class="col-md-6">
                      <%= f.label :remember_me, "Se rappeler de moi", class:"modal-title" %>
                    </div>
                    <div class="col-md-6">
                      <%= f.input :remember_me, label: false, as: :boolean if devise_mapping.rememberable? %>
                    </div>
                  </div>

                    <div class="col-md-6 padded flexed-center">
                    <%= f.button :submit, "Se connecter", class:"btn-first" %>
                    </div>
                    <div class="col-md-6 padded flexed-center">
                    <div class="btn-first">
                      <%- if devise_mapping.omniauthable? %>
                        <%- resource_class.omniauth_providers.each do |provider| %>
                      <%= link_to "Facebook", omniauth_authorize_path(resource_name, provider) %>
                      <% end -%>
                    </div>
                    </div>

                <% end %>
                <div class="padded" style="margin-top: 2rem"></div>
                <div class="col-md-6 padded flexed-center">
                  <button class="btn-first">
                    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
                      <%= link_to "Creer un compte", new_registration_path(resource_name) %><br />
                    <% end -%>
                  </button>
                </div>
                <div class="col-md-6 padded flexed-center">
                  <button class="btn-first">
                    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
                      <%= link_to "Mot de passe oublié ? ", new_password_path(resource_name) %><br />
                    <% end -%>
                  </button>
                </div>
                <% end -%>
                <p>Pour déposer un commentaire ou contacter un guide, il est necessaire d'être connecté.</p>
              </div>

            </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-soguide">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-soguide-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-soguide-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Accueil", root_path, class: "navbar-soguide-item navbar-soguide-link" %>
      <%= link_to "Destinations", countries_path, class: "navbar-soguide-item navbar-soguide-link" %>
      <%= link_to "Conseils", "#", class: "navbar-soguide-item navbar-soguide-link" %>
      <%= link_to "A propos", "#", class: "navbar-soguide-item navbar-soguide-link" %>
      <%= link_to "Contact", "#", class: "navbar-soguide-item navbar-soguide-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-soguide-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-soguide-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
    <button type="button" class="btn-first" data-toggle="modal" data-target="#myModal">
    <span>Se connecter</span>
    </button>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-soguide-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-soguide-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>




<%= render 'shared/log_in_modal' %>