config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :countries, param: :name, :only => [:show]
  resources :guides
  get 'trouver-un-guide', to: 'countries#index', as: :countries
  get 'pages/a_savoir'
  get 'admin/upload-guides', to: 'guides#upload_guides', as: :upload_guides
  post 'admin/upload-guides', to: 'guides#post_upload_guides', as: :post_upload_guides
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :traveler
  belongs_to :guide
end

app/models/country.rb
class Country < ApplicationRecord
  has_one :country_photo, dependent: :destroy
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/country_offering.rb
class CountryOffering < ApplicationRecord
  belongs_to :guide
  belongs_to :country
end

app/models/country_photo.rb
class CountryPhoto < ApplicationRecord
  belongs_to :country
end

app/models/guide.rb
class Guide < ApplicationRecord
  belongs_to :guide_organization, optional: true
  belongs_to :guide_contact_info, optional: true
  belongs_to :user
  has_many  :country_offerings, dependent: :destroy
  has_many  :guide_specialities, dependent: :destroy
  has_many  :guide_reviews, dependent: :destroy
  has_many  :spoken_languages, dependent: :destroy
  extend FriendlyId
  friendly_id :full_name, use: :slugged


  def full_name
    unless self.user.nil?
    self.user.first_name + ' ' + self.user.last_name
    end
  end

end

app/models/guide_contact_info.rb
class GuideContactInfo < ApplicationRecord
end

app/models/guide_organization.rb
class GuideOrganization < ApplicationRecord
end

app/models/guide_review.rb
class GuideReview < ApplicationRecord
  belongs_to :guide
  belongs_to :review
  belongs_to :traveler
end

app/models/guide_speciality.rb
class GuideSpeciality < ApplicationRecord
  belongs_to :speciality
  belongs_to :guide
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/speciality.rb
class Speciality < ApplicationRecord
end

app/models/spoken_language.rb
class SpokenLanguage < ApplicationRecord
  belongs_to :language
  belongs_to :guide
end

app/models/traveler.rb
class Traveler < ApplicationRecord
  belongs_to :user
  has_many :guide_reviews
  extend FriendlyId
  friendly_id :full_name, use: :slugged


  def full_name
    self.user.first_name + ' ' + self.user.last_name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]
  has_one :guide
  has_one :traveler

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/models/visiting_interest.rb
class VisitingInterest < ApplicationRecord
  belongs_to :country
  belongs_to :traveler
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  def index
    @countries = Country.all
  end
  def show
    @country = Country.friendly.find(params[:name])
    @guides = CountryOffering.where(country_id: @country)
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
skip_before_action :authenticate_user!, only: [:show, :index, :upload_guides, :post_upload_guides]
  def show
    @guide = Guide.friendly.find(params[:id])
    @guide_specialities = GuideSpeciality.where(guide: @guide)
    @guide_reviews = GuideReview.where(guide: @guide)
  end

  def upload_guides
  end
  def post_upload_guides
    unless params[:xlsx].nil?
      filepath = params[:xlsx].path
      xlsx = Roo::Spreadsheet.open(filepath)
      xlsx = Roo::Excelx.new(filepath)
      xlsx.default_sheet = xlsx.sheets.first
      csv = xlsx.to_csv
      PopulateGuideBaseJob.perform_later(csv)
      redirect_to upload_guides_path, notice: 'Guide en cours de chargement :)'
    else
      render :upload_guides, error: "Veuillez selectionner un fichier"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/countries/index.html.erb
<div class="padded-little"></div>
<div class="padded-little"></div>
<div class="container">
  <div class="row" style="text-align: center;">
    <div class="col-md-12 col-xs-12">
        <h3 class="title-index">Choisissez votre destination et découvrez nos guides !</h3>
        <p class="sub-title-index">Nous vous proposons de choisir un de nos 100 guides parmi 16 destinations. Sélectionnez un pays pour avoir des informations essentielles comme connaître la meilleure période pour le visiter.</p>
          <div class="padded-little"></div>
          <% @countries.order("name").each do | country | %>
            <div class="col-md-3 col-xs-12 card-wrapper country">
              <div class="card" style="background-image:url('<%= cl_image_path country.country_photo.main, crop: :fill  %>')">
                <div class="card-category">
                  <p><%= country.name %> </p>
                </div>
                <div class="card-description">
                </div>
                <%= link_to "", country_path(country), class:"card-link" %>
              </div>
            </div>
        <% end %>
    </div>
  </div>
</div>

app/views/countries/show.html.erb
<div class="banner-country" style="background-image:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0,0,0,0.2)),url('<%=  cl_image_path @country.country_photo.main, crop: :fill %>')">
    <div class="banner-content">
        <h1 class="title-contries"> <%= @country.name %> </h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="padded"></div>
        <div class="col-md-8">
            <div class="guide-car-wrapper">
              <% @guides.each do |g | %>
              <div class="card-guide">
                <div class="guide-car-left-part">
                    <div class="pic-guide-left-part guide-show-pic-countries" id="card-pic-guide" style="background-image:url('<%= g.guide.main_photo %>')">
                    </div>
                </div>
                <%= link_to guide_path(g.guide) do %>
                <div class="guide-car-right-part">
                  <div class="up-part-flexed" style="display: flex;justify-content: space-between;">
                  <div class="title-guide-right-part">
                  <h3 style="margin:0px;font-weight: 500;"> <%= g.guide.user.first_name.capitalize %> <%= g.guide.user.last_name %> </h3>
                  </div>
                  <div class="flag-guide-right-part">
                    <% g.guide.spoken_languages.each do |l| %>
                    <%= cl_image_tag "http://res.cloudinary.com/dgq8rxb4v/image/upload/v1511622088/Flag_#{l.language.name}.png", alt: "", class:"img-flag" %>
                    <% end %>
                  </div>
                  </div>
                  <div class="region-guide-right-part">
                  <p style="font-size: 14px;"> <span style="color:#099c03">Régions :</span><%= g.guide.state %></p>
                  </div>
                  <div class="comment-guide-right-part">
                    <p style="font-size: 14px;"> <span style="color:#099c03"> D'après ses clients :</span>
                      <%= g.guide.description %>
                    </p>

                  </div>
                  <div class="down-part-flexed" style="display: flex;justify-content: space-between;">
                  <% g.guide.guide_specialities.each do |l| %>
                  <span><%= image_tag "#{l.speciality.name}.png", class:"mini-picto" %></span>
                  <% end %>
                  <% end %>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-3" style="background: white;display: flex;margin-top: 20px;height: 100%;box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 -1px 6px rgba(0, 0, 0, 0.23);flex-direction: column;align-content: center;">
          <div class="description-up-right-part" style="padding:6%;display: flex;flex-direction: column;justify-content: space-between;">
          <p style="font-size: 14px;color:black;"> <%= @country.description %> </p>
          <div class="padded" style="padding-bottom: 4%;"></div>
          <div style="display: flex;justify-content: center;">
            <button type="button" class="btn-default" id="go-down">En savoir plus</button>
          </div>
          </div>
          <div class="padded" style="padding-bottom: 5%"></div>
          <div class="photo-up-right-part" style="width: 111.5%;margin-left: -15px;background-image:url('<%= cl_image_path @country.country_photo.second, crop: :fill  %>')">
          </div>
          <div class="when-box" style="background-image:url('<%= asset_path("When_Afrique_du_Sud_1.png") %>')">
          </div>
        </div>

    </div>

</div>

<div class="test" id="im-down"></div>
<div class="padded-little"></div>
<div class="container" style="width: 100%;">
  <div class="row">
    <div class="col-md-6 country-page-left-btm-part" style="background: linear-gradient(-225deg, rgba(30, 30, 30, 0.53) 30%, rgba(46, 46, 46, 0.87) 80%);color: white;font-weight: 300;font-size: 15px;">
      <h3 style="color:white;">Un peu d'histoire et de culture !</h3>
      <p><%= @country.description %></p>
    </div>
    <div class="col-md-6 photo-btm-right-part" style="background-image:url('<%= cl_image_path @country.country_photo.third, crop: :fill  %>')">
    </div>
    <div class="col-md-6 photo-btm-right-part" style="background-image:url('<%= cl_image_path @country.country_photo.fourth, crop: :fill  %>')">
    </div>
    <div class="col-md-6 country-page-left-btm-part" style="font-weight: 300;font-size: 15px;">
      <h3 style="">Les choses à voir et visiter !</h3>
      <p><%= @country.best_period %></p>
    </div>
  </div>
</div>



<% content_for(:after_js) do %>
  <%= javascript_tag do %>
      $(document).ready(function() {
        $("#go-down").click(function() {
            $('html,body').animate({
                scrollTop: $("#im-down").offset().top},
                'slow');
        });
      });
  <% end %>
<% end %>

app/views/guides/show.html.erb
<div class="padded-little"></div>
<div class="padded"></div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card-guide-show" style="box-shadow: 0 3px 64px rgba(0, 0, 0, 0.16), 0 3px 60px rgba(0, 0, 0, 0.23);">
                <div class="guide-car-left-part">
                    <% guide_picture = @guide.user.facebook_picture_url || @guide.main_photo %>
                    <div class="pic-guide-left-part guide-show-pic" style="background-image:url('<%= cl_image_path guide_picture, crop: :fill %>')">
                    </div>
                </div>
                <div class="guide-car-right-part" style="border-bottom: 1px solid rgba(0,0,0,0.08);background: white;color: black;">
                    <div class="up-part-flexed" style="display: flex;justify-content: space-between;">
                        <div class="title-guide-right-part">
                            <h3 style="margin:0px;font-weight: 800;font-size: 34px;"> <%= @guide.user.first_name.capitalize %> <%= @guide.user.last_name %> </h3>
                        </div>
                    </div>
                  <div class="flexed">
                    <div class="left-part-card-guide">
                    <div class="region-guide-right-part" style="align-items:center;display: flex;justify-content: left;">
                        <%= image_tag 'map.png', class:'picto-guide' %>
                            <p style="font-size: 14px;"> <span style="color:#099c03;font-size: 16px;">Type de guide :</span>
                              <% @guide_specialities.each do |g| %>
                              <%= g.speciality.name %>
                              <% end %>
                              </p>
                    </div>
                    <div class="region-guide-right-part" style="align-items:center;display: flex;justify-content: left;">
                        <%= image_tag 'map.png', class:'picto-guide' %>
                            <p style="font-size: 14px;"> <span style="color:#099c03;font-size: 16px;">Régions :</span>
                              <%= @guide.state %>
                            </p>
                    </div>
                    <div class="region-guide-right-part flag-guide-right-part" style="align-items:center;display: flex;justify-content: left;">
                      <%= image_tag 'map.png', class:'picto-guide' %>
                      <p style="font-size: 14px;"> <span style="color:#099c03;font-size: 16px;">Langues :</span>
                    <% @guide.spoken_languages.each do |l| %>
                          <%= l.language.name %>
                    <% end %>
                      </p>

                          </p>
                    </div>
                    </div>
                    <div class="right-part-card-guide">
                    <div class="region-guide-right-part" style="align-items:center;display: flex;justify-content: left;">
                        <%= image_tag 'degree.png', class:'picto-guide' %>
                            <p style="font-size: 14px;"> <span style="color:#099c03;font-size: 16px;">Expérience :</span>
                                <%= @guide.guide_contact_info.years_experience %> ans</p>
                    </div>
                    <div class="region-guide-right-part" style="align-items:center;display: flex;justify-content: left;">
                        <%= image_tag 'degree.png', class:'picto-guide' %>
                            <p style="font-size: 14px;"> <span style="color:#099c03;font-size: 16px;">License :</span>
                                <%= @guide.guide_organization.license %>
                            </p>
                    </div>
                    <div class="region-guide-right-part" style="align-items:center;display: flex;justify-content: left;">
                        <%= image_tag 'degree.png', class:'picto-guide' %>
                            <p style="font-size: 14px;"> <span style="color:#099c03;font-size: 16px;">Associés :</span> Incomming soon !</p>
                    </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row" style="margin-bottom: 5%">
        <div class="col-md-6">
            <h3 style="color:#099c03;padding-left:2%; font-weight: 400;">Contacter ce guide !</h3>
              <div class="contact-form-guide-show">
                <% unless current_user %>
                <p>Veuillez vous connecter pour contacter ce guide !</p>
                  <button type="button" class="btn-first" data-toggle="modal" data-target="#myModal">
                    <span>Se connecter</span>
                  </button>
                <% end %>
              </div>
        </div>
        <div class="col-md-6">
          <div class="guide-video-square">
            <iframe width="555" height="290" src="https://www.youtube.com/embed/TPdZvFuR8Ew" frameborder="0" allowfullscreen></iframe>
          </div>
        </div>
        <h3 style="color:#099c03;padding:2%; font-weight: 400;">Ils ont voyagé avec guide et le recommandent !</h3>
        <div class="col-md-12 all-messages-guide-show">
            <% @guide_reviews.each do |guidereview| %>
              <div class="col-md-12">
                <div class="message" style="border-bottom: 1px solid #80808054;">
                  <%= image_tag "#{guidereview.traveler.user.facebook_picture_url}", class: "avatar-small rounded"%>
                <div class="message-body">
                  <p>
                    <span class="green" style="font-weight: 500;">
                      <%= guidereview.traveler.user.first_name %> <%= guidereview.traveler.user.first_name %>,
                    </span>
                  <%= guidereview.review.fake_date.strftime("%e %b %Y") %> : </p>
                  <p style="color:black;white-space: pre-line;"><%= guidereview.review.content %></p>
                </div>
                </div>
              </div>
            <% end %>
        </div>
        <div class="row">
          <% @guide.country_offerings.each do |co| %>
          <div class="col-md-12">
            <h3 style="color:#099c03;padding:2%; font-weight: 400;">Vous souhaitez contacter d'autres guides en
              <%= co.country.name %>
              <div class="col-md-12">
                  <div class="col-md-3 card-wrapper">
                    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= @guide.main_photo %>')">
                      <div class="card-category">
                        <%= co.guide.user.first_name %>
                      </div>
                      <div class="card-description">
                      </div>

                    </div>
                    <p class="index-card-title"></p>
                  </div>
              </div>
          <% end %>
          </div>

        </div>
    </div>
</div>
<%= render 'shared/log_in_modal' %>

app/views/guides/upload_guides.html.erb
  <%= form_tag(post_upload_guides_path, method: "post", multipart: true) do %>
    <%= file_field_tag :xlsx, accept: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' %>
    <i class="fa fa-arrow-up" style="font-size: 49px;"></i>
    <%= submit_tag "Importer mon xlsx", class: 'submit-upload-file' %>
  <% end %>